// <auto-generated />
namespace Octet.Calendar.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsActive_Property_Added_to_Calendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsActive_Property_Added_to_Calendar));
        
        string IMigrationMetadata.Id
        {
            get { return "201509161133053_IsActive_Property_Added_to_Calendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
